# Generated by Django 2.2.15 on 2020-10-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_espanol', models.TextField(blank=True, null=True)),
                ('cita_APA_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_ingles', models.TextField(blank=True, null=True)),
                ('cita_APA_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('investigador_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.IntegerField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creator_date', models.IntegerField(blank=True, null=True)),
                ('last_update_id', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('evento_tipo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_hasta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades IIEP',
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_espanol', models.TextField(blank=True, null=True)),
                ('titulo_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_ingles', models.TextField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creator_date', models.IntegerField(blank=True, null=True)),
                ('last_update_id', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.IntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('director_id', models.IntegerField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proyectos IIEP',
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('investigador_id', models.IntegerField(blank=True, null=True)),
                ('subarea_id', models.PositiveIntegerField(blank=True, null=True)),
                ('texto_ingles', models.TextField(blank=True, null=True)),
                ('titulo_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_espanol', models.TextField(blank=True, null=True)),
                ('cita_bibliografica', models.CharField(blank=True, max_length=255, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('es_iiep', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creator_date', models.IntegerField(blank=True, null=True)),
                ('last_update_id', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.IntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('director_id', models.IntegerField(blank=True, null=True)),
                ('categoria_id', models.IntegerField(blank=True, null=True)),
                ('id_viejo', models.IntegerField(blank=True, null=True)),
                ('institucion_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones IIEP',
                'db_table': 'publicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('palabras_clave', models.CharField(max_length=50, null=True)),
                ('titulo_grado_espanol', models.CharField(max_length=50)),
                ('texto_espanol', models.CharField(max_length=500)),
                ('texto_corto_espanol', models.CharField(max_length=250, null=True)),
                ('institucion_grado', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('cv_espanol', models.FileField(null=True, upload_to='cv')),
            ],
            options={
                'verbose_name_plural': 'Investigadores IIEP',
                'db_table': 'investigadores',
            },
        ),
    ]
