# Generated by Django 2.2.15 on 2020-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiep', '0002_auto_20201021_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('copete_espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_espanol', models.TextField(blank=True, null=True)),
                ('titulo_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('copete_ingles', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_ingles', models.TextField(blank=True, null=True)),
                ('fecha', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('eliminado', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creator_date', models.IntegerField(blank=True, null=True)),
                ('last_update_id', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Novedades IIEP',
                'db_table': 'novedades',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name_plural': 'Actividades IIEP'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': False, 'ordering': ['-id'], 'verbose_name_plural': 'Proyectos IIEP'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name_plural': 'Publicaciones IIEP'},
        ),
    ]
