# Generated by Django 2.2.15 on 2020-09-18 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigador',
            options={'verbose_name_plural': 'Integrantes'},
        ),
        migrations.RemoveField(
            model_name='dato',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='asociados',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='asociados',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='copete',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='asociados',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autores',
        ),
        migrations.AddField(
            model_name='actividad',
            name='integrantes',
            field=models.ManyToManyField(to='app.Investigador'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='titulo', help_text='Titulo del evento', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='integrantes',
            field=models.ManyToManyField(to='app.Investigador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='integrantes',
            field=models.ManyToManyField(to='app.Investigador'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='integrantes',
            field=models.ManyToManyField(to='app.Investigador'),
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table=None,
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(help_text='Titulo o nombre del archivo', max_length=300)),
                ('archivo', models.FileField(upload_to='uploads/files/')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Actividad')),
                ('dato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Dato')),
                ('novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Novedad')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Proyecto')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Publicacion')),
                ('usuario_creacion', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
