# Generated by Django 2.2.15 on 2020-09-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200918_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigador',
            options={'verbose_name': 'integrante', 'verbose_name_plural': 'Integrantes'},
        ),
    ]
