# Generated by Django 2.2.15 on 2020-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200918_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='tipo',
            field=models.CharField(choices=[('nn', '----------'), ('inv', 'Investigador/a'), ('aso', 'Asociado/a'), ('bec', 'Becario/a'), ('aux', 'Auxiliar'), ('otr', 'Otro/a')], default='nn', max_length=3),
        ),
    ]
