# Generated by Django 2.2.15 on 2020-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200928_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='categoria',
            field=models.CharField(choices=[('nn', '----------'), ('ene', 'Energia y ambiente'), ('sec', 'Datos sectoriales'), ('mat', 'Datos matriciales'), ('com', 'Comercio')], default='nn', max_length=3),
        ),
    ]
