# Generated by Django 2.2.15 on 2020-10-07 18:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_investigador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='biografia',
            field=ckeditor.fields.RichTextField(default='biografia', help_text='Biografia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='investigadores/cv/'),
        ),
        migrations.AddField(
            model_name='investigador',
            name='orcid',
            field=models.CharField(default='0000-0000-0000-0000', help_text='Numero ORCID (xxxx-xxxx-xxxx-xxxx)', max_length=30),
            preserve_default=False,
        ),
    ]
