# Generated by Django 2.2.15 on 2020-10-09 00:10

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201008_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='link',
            field=models.URLField(blank=True, help_text='Formulario de registro', null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='actividades/logos/'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
    ]
