# Generated by Django 2.2.15 on 2020-10-21 13:54

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201021_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='flyer',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='actividades/flyers/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='doi',
            field=models.URLField(blank=True, help_text='Link DOI', null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='titulo', help_text='Titulo de la Publicacion', max_length=300),
            preserve_default=False,
        ),
    ]
