# Generated by Django 2.2.15 on 2020-10-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201021_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigadorIIEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('palabras_clave', models.CharField(max_length=50, null=True)),
                ('titulo_grado_espanol', models.CharField(max_length=50)),
                ('texto_espanol', models.CharField(max_length=500)),
                ('texto_corto_espanol', models.CharField(max_length=250, null=True)),
                ('institucion_grado', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('cv_espanol', models.FileField(null=True, upload_to='cv')),
            ],
            options={
                'verbose_name_plural': 'Investigadores IIEP',
                'db_table': 'investigadores',
            },
        ),
    ]
