# Generated by Django 2.2.15 on 2020-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegMIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacional', models.FileField(upload_to='uploads/files/in/')),
                ('regional', models.FileField(upload_to='uploads/files/in/')),
                ('sector', models.FileField(upload_to='uploads/files/in/')),
            ],
            options={
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
