# Generated by Django 2.2.15 on 2020-10-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pde', '0002_auto_20201015_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regmip',
            old_name='grp',
            new_name='nacional',
        ),
        migrations.RenameField(
            model_name='regmip',
            old_name='mip',
            new_name='regional',
        ),
        migrations.RenameField(
            model_name='regmip',
            old_name='vbps',
            new_name='sector',
        ),
    ]
