# Generated by Django 2.2.15 on 2020-10-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pde', '0003_auto_20201015_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo del video', max_length=50)),
                ('link', models.URLField(help_text='Link del video')),
                ('tutorial', models.FileField(blank=True, null=True, upload_to='publicaciones/tutoriales/')),
            ],
        ),
    ]
