# Generated by Django 2.2.15 on 2020-10-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pde', '0004_videotutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'verbose_name_plural': 'Tutorial'},
        ),
    ]
